export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_CONFIRM_REQUEST = "USER_CONFIRM_REQUEST";
export const USER_CONFIRM_SUCCESS = "USER_CONFIRM_SUCCESS";
export const USER_CONFIRM_ERROR = "USER_CONFIRM_ERROR";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";

export const GET_RANDOM_STRING_REQUEST = "GET_RANDOM_STRING_REQUEST";
export const GET_RANDOM_STRING_SUCCESS = "GET_RANDOM_STRING_SUCCESS";
export const GET_RANDOM_STRING_ERROR = "GET_RANDOM_STRING_ERROR";
